Sub AddTextWithPolylineArea()
    Dim doc As AcadDocument
    Dim ssSet As AcadSelectionSet
    Dim polyline As AcadLWPolyline
    Dim minPt As Variant
    Dim maxPt As Variant
    Dim centerPoint(0 To 2) As Double
    Dim area As Double
    Dim textObj As AcadText
    Dim promptMsg As String
    Dim pickedObj As AcadEntity
    Dim pickFirst As Boolean
    Dim continueLoop As Boolean
    
    ' 获取当前AutoCAD文档
    Set doc = ThisDrawing
    
    ' 创建一个新的选择集
    On Error Resume Next
    Set ssSet = doc.SelectionSets.Add("PolylineSS")
    If Err.Number <> 0 Then
        ' 如果选择集已经存在，则获取它并清空
        Set ssSet = doc.SelectionSets.Item("PolylineSS")
        ssSet.Clear
        Err.Clear
    End If
    On Error GoTo 0
    
    ' 初始化循环标志
    continueLoop = True
    
    ' 循环提示用户选择多段线
    Do While continueLoop
        ' 清空选择集
        Set pickedObj = Nothing
        On Error Resume Next
        ' 提示用户选择一个多段线
        promptMsg = "请选择一个多段线 (按回车结束): "
        
        doc.Utility.GetEntity pickedObj, promptMsg
        On Error GoTo 0
        ' 检查用户是否取消选择
        If pickedObj Is Nothing Then
            MsgBox "未选择任何对象，程序结束。", vbInformation, "选择取消"
            Exit Do
        End If
        
        ' 检查选择的对象是否为轻量级多段线
        If TypeName(pickedObj) = "IAcadLWPolyline" Then
            Set polyline = pickedObj
            
            ' 计算多段线的面积
            area = polyline.area
            
            ' 获取多段线的最小和最大边界点
            polyline.GetBoundingBox minPt, maxPt
            
            
            ' 计算多段线的中心点
            centerPoint(0) = (minPt(0) + maxPt(0)) / 2
            centerPoint(1) = (minPt(1) + maxPt(1)) / 2
            centerPoint(2) = 0 ' Z坐标为0，因为我们是在2D平面上工作
            
            ' 添加文本对象
            Set textObj = doc.ModelSpace.AddText("面积: " & Format(area, "0.00"), centerPoint, doc.GetVariable("TEXTSIZE"))
            textObj.Alignment = acAlignmentMiddleCenter ' 设置文本对齐方式为中心对齐
            textObj.TextAlignmentPoint = centerPoint
            ' 刷新屏幕以显示新添加的文本
            doc.Regen acAllViewports
            
            ' 提示用户
            'MsgBox "已成功添加面积文本到多段线的中心位置。", vbInformation, "操作完成"
        Else
            MsgBox "选择的对象不是多段线，请重新选择。", vbExclamation, "无效选择"
        End If
        
        ' 询问用户是否继续
       ' continueLoop = (MsgBox("是否继续选择多段线？", vbYesNo + vbQuestion, "继续操作") = vbYes)
        
    Loop
    
    ' 清理
    ssSet.Delete
End Sub

